export const DIMENSIONS = {
  CANVAS_WIDTH: window.innerWidth / 2,
  CANVAS_HEIGHT: window.innerHeight,
};

export const SPEED = 5;

export const PLAYER_DIMENSIONS = {
  PLAYER_WIDTH: 150,
  PLAYER_HEIGHT: 150,
};

export const LANE_POSITION = {
  LEFT_LANE:
    ((1 / 3) * DIMENSIONS.CANVAS_WIDTH) / 2 -
    PLAYER_DIMENSIONS.PLAYER_WIDTH / 2,
  MID_LANE: DIMENSIONS.CANVAS_WIDTH / 2 - PLAYER_DIMENSIONS.PLAYER_WIDTH / 2,
  RIGHT_LANE:
    (DIMENSIONS.CANVAS_WIDTH * (2 / 3) + DIMENSIONS.CANVAS_WIDTH) / 2 -
    PLAYER_DIMENSIONS.PLAYER_WIDTH / 2,
};

export const DIFFERENCE = LANE_POSITION.MID_LANE - LANE_POSITION.LEFT_LANE;

export const SIDE_SPEED = 10;
